### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by james34602** [Xiangwk/Text3D_with_OpenGL#1]
Memory leak occur inside game loop function call geometries[i].draw(text_shader);

To prevent this:
void Geometry::draw(MyShader shader)
{
	updataPrimitives();
	//for (auto &p : _primitive_list)
	p.draw(shader);
++++++++++
	p.deleteBuffers();
++++++++++
}
Will solve the problem.

**Comment by Xiangwk** [comment]
Oh, yes you are right! Thank you very much!

**Comment by Xiangwk** [comment]
This is a design problem, it should not be used by this way. The updataPrimitives() should not be called in draw(), this lead to not only memory leak, but also an efficiency problem—— the vertex data is no need to transmit to GPU in every frame! So I have updated code and solve the two problems. Have fun and thanks again!

**Comment by james34602** [comment]
Great
