### ISSUE TITLE
字体锯齿问题

### ISSUE THREAD

**Issue by sway913** [Xiangwk/Text3D_with_OpenGL#2]
你好，3D文字边缘锯齿问题有没有比较好的处理方案？谢谢！

**Comment by Xiangwk** [comment]
呃，你是指文字曲线的细分程度还是说显示出来的边缘锯齿？如果是细分的话需要处理法向量，这个暂时还没有弄~如果是边缘抗锯齿的话，用opengl自己的抗锯齿就好了，命令是glEnable(GL_MULTISAMPLE)，但是在用glfw创建窗口的时候需要开启超采样，glfwWindowHint(GLFW_SAMPLES, 4);

**Comment by sway913** [comment]
是显示出来的边缘锯齿。
![text](https://user-images.githubusercontent.com/9814915/34380981-803aa710-eb40-11e7-9db3-1825b344e93d.jpg)
就像上面这图，感觉边缘就是不平滑。

**Comment by Xiangwk** [comment]
恩恩，这种就用opengl写好的抗锯齿就可以

**Comment by sway913** [comment]
好的。请教下，这种方式实现的文字生成位图会有锯齿吗？

**Comment by sway913** [comment]
经过试用，感觉很不错，能达到项目要求，谢谢你的付出。
